Repository Sanket1308/javascript-quote-generator, pull requests merged in 2022-10, with the labels that each got.

#12 Feature: Added new tweet button
  index.html
  script.js
  styles.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#37 changed the path of image source in style.css
  css/styles.css
Labels: bug, hacktoberfest, hacktoberfest-accepted

#39 added media query
  css/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#42 Smooth transition of background images[Fix issue #32]
  css/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#50 Feat: Copy Quote
  css/styles.css
  index.html
  js/script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#59 Updated contributing.md file
  CONTRIBUTING.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#54 Feature1 for review again
  README.md
  images/screenshot-live-prjct.png
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#63 added smooth background image transition
  css/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
